export enum BusinessIndustry {
  UNSET,
  ACCOMMODATION,
  FOOD,
  BUSINESS_SUPPORT,
  AGRICULTURE,
  FORESTRY,
  FISHING,
  HUNTING,
  ARTS,
  CONSTRUCTION,
  EDUCATIONAL,
  FINANCE,
  HEALTHCARE,
  MANUFACTURING,
  MINING,
  SCIENTIFIC,
  TECHNICAL_SERVICES,
  REAL_ESTATE,
  RETAIL_TRADE,
  TRANSPORTATION,
  WAREHOUSING,
}

export const BusinessIndustrySet = [
  { key: 'enumOptions.businessIndustries.UNSET', value: BusinessIndustry.UNSET },
  { key: 'enumOptions.businessIndustries.ACCOMMODATION', value: BusinessIndustry.ACCOMMODATION },
  { key: 'enumOptions.businessIndustries.FOOD', value: BusinessIndustry.FOOD },
  {
    key: 'enumOptions.businessIndustries.BUSINESS_SUPPORT',
    value: BusinessIndustry.BUSINESS_SUPPORT,
  },
  { key: 'enumOptions.businessIndustries.AGRICULTURE', value: BusinessIndustry.AGRICULTURE },
  { key: 'enumOptions.businessIndustries.FORESTRY', value: BusinessIndustry.FORESTRY },
  { key: 'enumOptions.businessIndustries.FISHING', value: BusinessIndustry.FISHING },
  { key: 'enumOptions.businessIndustries.HUNTING', value: BusinessIndustry.HUNTING },
  { key: 'enumOptions.businessIndustries.ARTS', value: BusinessIndustry.ARTS },
  { key: 'enumOptions.businessIndustries.CONSTRUCTION', value: BusinessIndustry.CONSTRUCTION },
  { key: 'enumOptions.businessIndustries.EDUCATIONAL', value: BusinessIndustry.EDUCATIONAL },
  { key: 'enumOptions.businessIndustries.FINANCE', value: BusinessIndustry.FINANCE },
  { key: 'enumOptions.businessIndustries.HEALTHCARE', value: BusinessIndustry.HEALTHCARE },
  { key: 'enumOptions.businessIndustries.MANUFACTURING', value: BusinessIndustry.MANUFACTURING },
  { key: 'enumOptions.businessIndustries.MINING', value: BusinessIndustry.MINING },
  { key: 'enumOptions.businessIndustries.SCIENTIFIC', value: BusinessIndustry.SCIENTIFIC },
  {
    key: 'enumOptions.businessIndustries.TECHNICAL_SERVICES',
    value: BusinessIndustry.TECHNICAL_SERVICES,
  },
  { key: 'enumOptions.businessIndustries.REAL_ESTATE', value: BusinessIndustry.REAL_ESTATE },
  { key: 'enumOptions.businessIndustries.RETAIL_TRADE', value: BusinessIndustry.RETAIL_TRADE },
  { key: 'enumOptions.businessIndustries.TRANSPORTATION', value: BusinessIndustry.TRANSPORTATION },
  { key: 'enumOptions.businessIndustries.WAREHOUSING', value: BusinessIndustry.WAREHOUSING },
];
